### ISSUE TITLE
[proposal] open on GitHub button

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/contribute.dev#11]
Just to file an issue irrelevant to adding a project. Or it will be sidetracking?

**Comment by nisarhassan12** [comment]
@akosyakov I have manually sorted the json data by stars and then closed the issue. Does you meant to have a filter with sort by stars option?

**Comment by nisarhassan12** [comment]
@akosyakov I'm sorry I'm not able to understand what do you mean by this. It would be great if you can explain this in a bit more detail :slightly_smiling_face:

**Comment by akosyakov** [comment]
I mean open github repo for contribute.dev website.

**Comment by nisarhassan12** [comment]
@jankeromnes As you said we are going to have contribute.dev in the Projects list once we have a community around it I agree that it would make more sense in the Projects list then.

I also agree with @akosyakov and also think that for now, we need to have a button alongside "File an Issue" button that opens a workspace for contribute.dev. So that the users can edit the site and fix bugs themselves. What do you say?

**Comment by jankeromnes** [comment]
Good idea! Maybe a small clickable GitHub icon at the bottom of the website?

**Comment by jankeromnes** [comment]
Fixed.
