### ISSUE TITLE
Please add my project

### ISSUE THREAD

**Issue by steviebeenz** [gitpod-io/contribute.dev#17]
Trapteamccnz/trapteammainsite

**Comment by nisarhassan12** [comment]
Sorry! @steviebeenz we can't add your project because The goal of [contribute.dev](https://contribute.dev) is to: 
- show aspiring OSS newcomers cool projects they could join & start contributing to instantly.
- show maintainers how to make their projects newcomer-friendly, esp. by fully automating their dev setup. 

For a project to be added to the list, it's a must that Project should have: A minimum of 500 stars and 10 contributors.
