### ISSUE TITLE
Improve Chrome Devtools Audit score

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/contribute.dev#20]
It currently looks like this:

<img width="735" alt="Screenshot 2019-08-28 at 17 29 33" src="https://user-images.githubusercontent.com/599268/63870044-7d4f6a00-c9b9-11e9-8a90-e6b36386b04a.png">

**Comment by jankeromnes** [comment]
Many images seem unnecessarily heavy, and could probably be optimized in a few seconds by an online tool like https://tinypng.com/ (also supports JPG)

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes This is what it looks like now: 

![image](https://user-images.githubusercontent.com/46004116/63913237-db775e00-ca48-11e9-9160-a80de454ba5a.png)

We have this problem related to SEO: 
![image](https://user-images.githubusercontent.com/46004116/63913309-25f8da80-ca49-11e9-9c29-c35be63d4511.png)

which is caused by this "Learn More" Button Can we change the text to some thing else :slightly_smiling_face: ?
![image](https://user-images.githubusercontent.com/46004116/63913343-4de83e00-ca49-11e9-94c5-a06838deaded.png)

**Comment by jankeromnes** [comment]
Great work!

We'll probably change that entire section before launch, so please don't spend too much time on optimizing it yet. 🙂 

But maybe something like "Introducing Gitpod"? (Or "Learn more about Gitpod"?)

**Comment by nisarhassan12** [comment]
Ok. Thanks :)

**Comment by jankeromnes** [comment]
Now looks like this:

<img width="731" alt="Screenshot 2019-08-29 at 18 13 07" src="https://user-images.githubusercontent.com/599268/63957455-b1de2700-ca88-11e9-836c-41c3b203f652.png">

I guess that's good enough to close this issue. 🙂 🎉 🏅
