### ISSUE TITLE
Please add https://github.com/milligram/milligram

### ISSUE THREAD

**Issue by cjpatoilo** [gitpod-io/contribute.dev#32]

**Comment by svenefftinge** [comment]
https://github.com/milligram/milligram/pull/237

**Comment by jankeromnes** [comment]
Hi @cjpatoilo! @svenefftinge has put some efforts into creating a welcoming & fully-automated dev setup for your project. 🙂 Please take a look at https://github.com/milligram/milligram/pull/237 when you have time.

**Comment by jankeromnes** [comment]
Awesome! Many thanks @cjpatoilo, I've just tried the automated setup, and it works great:

<img width="1552" alt="Screenshot 2020-05-04 at 19 11 22" src="https://user-images.githubusercontent.com/599268/80993269-17b25800-8e3b-11ea-8336-14e3350891c1.png">

But this issue is not actually fixed though, since milligram is not yet on https://contribute.dev. So re-opening.

**Comment by jankeromnes** [comment]
Added! 🎉 

<img width="1116" alt="Screenshot 2020-05-04 at 19 28 06" src="https://user-images.githubusercontent.com/599268/80994758-6c56d280-8e3d-11ea-9a39-b6264a376acb.png">
