### ISSUE TITLE
Buttons have no function

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/contribute.dev#4]
The badges and the github stars should provide the usual functionality (i.e. link).

**Comment by svenefftinge** [comment]
I think we need to use the original badges, no?

**Comment by svenefftinge** [comment]
Same for the GH stars. Otherwise we'd need to manually update and regenerate to have up to date numbers.

**Comment by jankeromnes** [comment]
> Same for the GH stars. Otherwise we'd need to manually update and regenerate to have up to date numbers.

The GitHub star counter should already stay up-to-date, since it's using a live shields.io badge:

[![stars](https://img.shields.io/github/stars/freeCodeCamp/freeCodeCamp.svg?style=social)](https://github.com/freeCodeCamp/freeCodeCamp)

> The badges and the github stars should provide the usual functionality (i.e. link).

I agree that all badges should be links to somewhere that makes sense.

For example, the stars badge should link to either the repository (e.g. https://github.com/freeCodeCamp/freeCodeCamp), or to the list of people who have starred the repository (e.g. https://github.com/freeCodeCamp/freeCodeCamp/stargazers).

**Comment by jankeromnes** [comment]
> I think we need to use the original badges, no?

I agree that the badges we're listing on contribute.dev should definitely be those actually used by the projects on GitHub, not inventions from us.

For example, https://github.com/freeCodeCamp/freeCodeCamp currently has these 4 badges in README.md:

- [![Build Status](https://travis-ci.org/freeCodeCamp/freeCodeCamp.svg?branch=staging)](https://travis-ci.org/freeCodeCamp/freeCodeCamp)
- [![Pull Requests Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat)](http://makeapullrequest.com)
- [![first-timers-only Friendly](https://img.shields.io/badge/first--timers--only-friendly-blue.svg)](http://www.firsttimersonly.com/)
- [![Open Source Helpers](https://www.codetriage.com/freecodecamp/freecodecamp/badges/users.svg)](https://www.codetriage.com/freecodecamp/freecodecamp)

So I think that on contribute.dev, we should decide to use some of these badges, and also keep the original URL each badge links to.

Maybe `build | passing` doesn't make sense on contribute.dev, so we can omit it, but the `contributor | friendly` badge we currently have for FreeCodeCamp doesn't seem to exist, so we should probably remove it.

Then, I'm not quite sure about the `PRs | welcome` and `first-timers-only | friendly` tags, because they're just link to external website that are not really related to FreeCodeCamp (i.e. makeapullrequest.com and www.firsttimersonly.com).
