### ISSUE TITLE
https://github.com/eclipse/openvsx

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/contribute.dev#75]

**Comment by jankeromnes** [comment]
@nisarhassan12 Excellent idea! As discussed on Slack, please add this project to the list if you feel that the contribution experience is awesome, welcoming and frictionless. 🙂

(Replies to the questions from the issue template are generally a good indicator, but since you're a committer to both OpenVSX and contribute.dev, you're in a good position to know whether it's a good fit. 😄)
